### PR TITLE
Fix issue with some tasks not being linked to structures

### LINKED ISSUE #360: Investigate why some tasks are not linked to structures
There are reports that some tasks are not linked to structures and thus do not show up in the mobile client.

This is based on the discussion here: https://onaio.slack.com/archives/CBSU8L2SC/p1565055505025300

We should investigate what can cause this and document it and fix it.

### PR DESCRIPTION
**Pull request by Rkareko**
Resolves #360

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/sync/LocationTaskIntentService.java [hunk 1]
```diff
@@ -85,6 +86,8 @@ private void doSync() {
 
         TaskRepository taskRepository = RevealApplication.getInstance().getContext().getTaskRepository();
         taskRepository.updateTaskStructureIdFromStructure(syncedStructures);
+        taskRepository.updateTaskStructureIdsFromExistingStructures();
+        taskRepository.updateTaskStructureIdsFromExistingClients(FAMILY_MEMBER);
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/sync/LocationTaskIntentService.java]: This should not be called since Clients are not synced by this service
