### PR TITLE
Fix bug archiving causes sync failure

### LINKED ISSUE #1189: Sync Issue Following a user dropping a structure and archiving it while still Offline
- [ ] On the Thailand APK there is an issue reported where a test made on the Thai apk showed that a user who drops a structure when offline and then goes ahead to archive it, will not be able to complete sync and the red bubble on the hamburger menu will persist.

### PR DESCRIPTION
**Pull request by githengi**
Resolves #1189 

related to https://github.com/OpenSRP/opensrp-client-core/pull/710

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java [hunk 1]
```diff
@@ -227,7 +227,7 @@ public static Boolean getDrawOperationalAreaBoundaryAndLabel() {
      * @return validateFarStructures
      */
     public static Boolean validateFarStructures() {
-        return Boolean.valueOf(getGlobalConfig(CONFIGURATION.VALIDATE_FAR_STRUCTURES, BuildConfig.VALIDATE_FAR_STRUCTURES + ""));
+        return false;
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java:230]:
```suggestion
        return Boolean.valueOf(getGlobalConfig(CONFIGURATION.VALIDATE_FAR_STRUCTURES, BuildConfig.VALIDATE_FAR_STRUCTURES + ""));
```

**Review by Rkareko — APPROVED** [review]

**Review by Rkareko — APPROVED** [review]
