### PR TITLE
Use toast instead of Snackbar for sync messages

### LINKED ISSUE #1231: Syncing snack bar prevents users from clicking any buttons underneath it
https://smartregister.atlassian.net/browse/RVL-1449

**Problem**
The Syncing message is a snackbar and stays on the screen until sync is successful or sync fails
The snackbar (located at the bottom of the screen) hides any buttons underneath it and users are unable to click these hidden buttons. See sample screenshot below.
image

**Potential solution**
Change the sync UI to be a toast message 

**Considerations**
- What are other potential solutions
- Could we reduce the snack bar and center it as has been done on other OpenSRP Apps. See sample below:
image

### PR DESCRIPTION
**Pull request by faidvd**
resolves #1231

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/view/ListTasksActivity.java [hunk 1]
```diff
@@ -844,26 +844,30 @@ public void onDestroy() {
...
     @Override
     public void onSyncInProgress(FetchStatus fetchStatus) {
         if (FetchStatus.fetched.equals(fetchStatus)) {
-            syncProgressSnackbar.show();
             return;
         }
-        syncProgressSnackbar.dismiss();
+        if (completedToastShown) return;
+        //To cover against consecutive sync starts firing, turn the flag off with delay
+        new Handler().postDelayed(() -> startedToastShown = false, 5000);
```
Comment (Rkareko) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/view/ListTasksActivity.java:862]: Move this value to constants file

**Comment by Rkareko** [comment]
@faidvd the translation for  `Sync Started` has been added on the sheet [here](https://docs.google.com/spreadsheets/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit?folder=1MN5J-PK6KUOHC6gw3KKmf12vV-GQFPkr#gid=218216998) . Could you update it.

**Review by Rkareko — APPROVED** [review]
