### PR TITLE
Add file provider to fix error with taking images in forms

### LINKED ISSUE #755: Adding a photo of the checlikst on the IRS Field Officer Form crashes the app
Login to the app
Go to the other form section on the hamburger menu
Click on one of the form eg IRS Field Officer.
Click on the edit form and scroll to the section that says: "Add a photo of today's checklist"
Observe how clicking that section crashes the app; either by closing that section and returning to the map page. Or How it crashes the app and closes it immediately
Screenshot_20200526_155838_org smartregister reveal

### PR DESCRIPTION
**Pull request by Rkareko**
Resolve #755

### CODE REVIEW

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5622582&bid=18417917)

File: opensrp-reveal/src/test/java/org/smartregister/reveal/util/RevealJsonFormUtilsTest.java [hunk 1]
```diff
@@ -229,6 +229,21 @@ public void testGetRefAppBednetDistributionForm() {
         assertEquals(JsonForm.REFAPP_BEDNET_DISTRIBUTION_FORM, actualFormName);
     }
 
+    @Test
+    public void testGetThailandCaseConfirmationForm() {
+        Whitebox.setInternalState(BuildConfig.class, BuildConfig.BUILD_COUNTRY, Country.THAILAND);
+        String actualFormName = revealJsonFormUtils.getFormName(Constants.EventType.CASE_CONFIRMATION_EVENT, CASE_CONFIRMATION);
```
Comment (keymane) [inline opensrp-reveal/src/test/java/org/smartregister/reveal/util/RevealJsonFormUtilsTest.java:235]: Codacy Issue found: [Unnecessary use of fully qualified name 'Constants.EventType.CASE_CONFIRMATION_EVENT' due to existing static import 'org.smartregister.reveal.util.Constants.EventType.CASE_CONFIRMATION_EVENT'](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5622582)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5622582&bid=18417917)

File: opensrp-reveal/src/test/java/org/smartregister/reveal/util/RevealJsonFormUtilsTest.java [hunk 2]
```diff
@@ -229,6 +229,21 @@ public void testGetRefAppBednetDistributionForm() {
...
+    public void testGetThailandCaseConfirmationForm() {
+        Whitebox.setInternalState(BuildConfig.class, BuildConfig.BUILD_COUNTRY, Country.THAILAND);
+        String actualFormName = revealJsonFormUtils.getFormName(CASE_CONFIRMATION_EVENT, CASE_CONFIRMATION);
+        assertEquals(JsonForm.THAILAND_CASE_CONFIRMATION_FORM, actualFormName);
+    }
+
+    @Test
+    public void testGetRefAppCaseConfirmationForm() {
+        Whitebox.setInternalState(BuildConfig.class, BuildConfig.BUILD_COUNTRY, Country.REFAPP);
+        String actualFormName = revealJsonFormUtils.getFormName(Constants.EventType.CASE_CONFIRMATION_EVENT, CASE_CONFIRMATION);
```
Comment (keymane) [inline opensrp-reveal/src/test/java/org/smartregister/reveal/util/RevealJsonFormUtilsTest.java:242]: Codacy Issue found: [Unnecessary use of fully qualified name 'Constants.EventType.CASE_CONFIRMATION_EVENT' due to existing static import 'org.smartregister.reveal.util.Constants.EventType.CASE_CONFIRMATION_EVENT'](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5622582)
