### PR TITLE
Skip reset task event during client processing

### LINKED ISSUE #646: Fix app crash after resetting a task
Steps to reproduce
- Open family profile view.
- Reset a blood screening task
- Navigate to map view
- Initiate a manual sync.
- After sync completes open the family profile view.
- App crashes due to a null pointer exception when setting the task action color in the Family Profile Tasks view.

Cause
- During client processing the `reset_task `  event is processed which results in a task being updated with a null `business_status` since the `reset_task ` event does not contain the business status in the `event.obs` object.

Fix
- Skip the `reset_task `  event during client processing.

### PR DESCRIPTION
**Pull request by Rkareko**
Resolves #646

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java [hunk 1]
```diff
@@ -114,6 +115,8 @@ public void processClient(List<EventClient> eventClients, boolean localEvents) {
                     processUpdateFamilyRegistrationEvent(event, eventClient.getClient(), clientClassification, localEvents);
                 } else if (eventType.equals(Constants.EventType.PAOT_EVENT)) {
                     operationalAreaId = processEvent(event, clientClassification, localEvents, JsonForm.PAOT_STATUS);
+                } else if (eventType.equals(TASK_RESET_EVENT)) {
```
Comment (keymane) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java]: Codacy Issue found: [Avoid empty if statements](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/TaskUtilsTests.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/presenter/StructureTasksPresenter.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/view/ListTasksActivity.java  3
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/InteractorUtilsTest.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/util/InteractorUtils.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286&bid=16581743)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- opensrp-reveal/src/main/java/org/smartregister/reveal/util/InteractorUtils.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java  1
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/TaskUtilsTests.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/presenter/StructureTasksPresenter.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/view/ListTasksActivity.java  3
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/InteractorUtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286&bid=16581743)

File: opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java (hunk 1 above)
Comment (keymane) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java]: Codacy Issue found: [Avoid empty if statements](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286)

**Comment by keymane** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- opensrp-reveal/src/main/java/org/smartregister/reveal/util/InteractorUtils.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/view/ListTasksActivity.java  3
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/TaskUtilsTests.java  1
- opensrp-reveal/src/test/java/org/smartregister/reveal/util/InteractorUtilsTest.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java  1
- opensrp-reveal/src/main/java/org/smartregister/reveal/presenter/StructureTasksPresenter.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286&bid=16581743)

File: opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java (hunk 1 above)
Comment (keymane) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/sync/RevealClientProcessor.java]: Codacy Issue found: [Avoid empty if statements](https://app.codacy.com/manual/OpenSRP/opensrp-client-reveal/pullRequest?prid=5033286)
