### PR TITLE
Fix photo not being displayed on form

### LINKED ISSUE #771: The photo taken at the checklist on the IRS Field Officer Form is not shown
Login to the app
Go to the other form section on the hamburger menu
Click on one of the form eg IRS Field Officer.
Click on the edit form and scroll to the section that says: "Add a photo of today's checklist"
After taking a picture observe how the picture taken is not there.
connected to: https://github.com/OpenSRP/opensrp-client-reveal/issues/755

### PR DESCRIPTION
**Pull request by Rkareko**
Resolves #771

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/activity/RevealJsonFormActivity.java [hunk 1]
```diff
@@ -45,6 +45,7 @@ public void initializeFormFragment() {
 
     @Override
     protected void onActivityResult(int requestCode, int resultCode, Intent data) {
+        super.onActivityResult(requestCode, resultCode, data);
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/activity/RevealJsonFormActivity.java:48]: could this be added if its not handled here
