### PR TITLE
Handle both Polygons and MultiPolygons when retrieving updated coordinates

### LINKED ISSUE #988: THAI-The app crashed when one tries to edit the foci boundary
Login to the app
Long press the boundary
Click on one of the circles and try to move it.
Click save and observe the crash
see video below

https://drive.google.com/file/d/161Vm2jKA51fvcgsVJyqKh6QhcBL4hhAm/view?usp=sharing

### LINKED ISSUE #989: THAI-The app crashes when on tries to login
Enter the user credentials:
thaiuser2/Amani123
Observe how the app crashes and closes.

### PR DESCRIPTION
**Pull request by Rkareko**
Resolves #988 
Resolves #989

### CODE REVIEW

File: opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java [hunk 1]
```diff
@@ -415,20 +415,26 @@ public static Boolean displayDistanceScale() {
...
+     * @param updatedGeometry The geometry of the updated feature
+     * @param originalGeometry The geometry of the original feature used to determine whether
+     *                         it was a MultiPolygon or a Polygon
      * @return
      */
-    public static JSONArray getCoordsFromGeometry(Geometry geometry) {
-        MultiPolygon multiPolygon = MultiPolygon.fromPolygons(Collections.singletonList((Polygon) geometry));
-        JSONObject multiPolygonJson;
-        JSONArray multiPolygonCoords = null;
+    public static JSONArray getCoordsFromGeometry(Geometry updatedGeometry, Geometry originalGeometry) {
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java:423]: Could we add a unit test for this

File: opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java [hunk 2]
```diff
@@ -415,20 +415,26 @@ public static Boolean displayDistanceScale() {
...
         try {
-            multiPolygonJson = new JSONObject(multiPolygon.toJson());
-            multiPolygonCoords = (JSONArray) multiPolygonJson.get("coordinates");
+            if (originalGeometry instanceof  MultiPolygon) {
+                MultiPolygon editedGeometryMultiPolygon = MultiPolygon.fromPolygons(Collections.singletonList((Polygon) updatedGeometry));
+                editedGeometryJson = new JSONObject(editedGeometryMultiPolygon.toJson());
+            } else {
+                editedGeometryJson = new JSONObject(updatedGeometry.toJson());
+            }
+            updatedCoords = (JSONArray) editedGeometryJson.get("coordinates");
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java:433]:
```suggestion
            updatedCoords =  editedGeometryJson.getJSONArray("coordinates");
```

File: opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java [hunk 3]
```diff
@@ -415,20 +415,26 @@ public static Boolean displayDistanceScale() {
...
-        JSONObject multiPolygonJson;
-        JSONArray multiPolygonCoords = null;
+    public static JSONArray getCoordsFromGeometry(Geometry updatedGeometry, Geometry originalGeometry) {
+        JSONObject editedGeometryJson ;
+        JSONArray updatedCoords = null;
         try {
-            multiPolygonJson = new JSONObject(multiPolygon.toJson());
-            multiPolygonCoords = (JSONArray) multiPolygonJson.get("coordinates");
+            if (originalGeometry instanceof  MultiPolygon) {
+                MultiPolygon editedGeometryMultiPolygon = MultiPolygon.fromPolygons(Collections.singletonList((Polygon) updatedGeometry));
```
Comment (githengi) [inline opensrp-reveal/src/main/java/org/smartregister/reveal/util/Utils.java:428]:
```suggestion
                 MultiPolygon editedGeometryMultiPolygon = MultiPolygon.fromPolygon((Polygon) updatedGeometry);
```
Can't this simplified to the above

**Review by githengi — APPROVED** [review]
